env.info("Red Iberia Ver 2.0")
env.info("Mission by Robert Graham")
env.info("Mission Script Loader Active")
env.info("Loading MOOSE")

dofile(lfs.writedir() .."rib\\scripts\\Moose.lua")
env.info("Loading MIST")
dofile(lfs.writedir() .."rib\\scripts\\mist_4_3_74.lua")
env.info("hHypeMan")
assert(loadfile("C:/HypeMan/HypeMan.lua"))() 
HypeMan.sendBotMessage("Red Iberia is Starting.....")
env.info("Loading Peristence")
HypeMan.sendBotMessage("Red Iberia Persistence Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\persistence.lua")
env.info("Loading Globals")
HypeMan.sendBotMessage("Red Iberia Globals Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\globals.lua")
env.info("Loading Rutils")
HypeMan.sendBotMessage("Red Iberia Utilities Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\rutils.lua")
env.info("Loading Slotblocker")
HypeMan.sendBotMessage("Red Iberia Slot blocker Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\slotblocking.lua")
env.info("Loading A2ACap")
HypeMan.sendBotMessage("Red Iberia Ai A2A Cap Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\a2acap.lua")
env.info("Loading Groupsaving")
HypeMan.sendBotMessage("Red Iberia Group Saving Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\simple_groupsaving.lua")
env.info("Loading CTLD")
HypeMan.sendBotMessage("Red Iberia CTLD Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\CTLD.lua")
env.info("Loading CTLD SAVE")
HypeMan.sendBotMessage("Red Iberia CTLD Group Saving Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\ctldsave.lua")
env.info("Loading CTLD STATIC SAVE")
HypeMan.sendBotMessage("Red Iberia CTLD Static Saving Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\ctld_static_save.lua")
env.info("Loading CTLD SCENERY")
HypeMan.sendBotMessage("Red Iberia Scenery Static Saving Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\simple_scenery_persistence.lua") 
env.info("Loading RIB SAVE")
HypeMan.sendBotMessage("Red Iberia Core Persistency Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\ribsave.lua") 
env.info("Loading Main")
HypeMan.sendBotMessage("Red Iberia Main Script Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\main_no_cv_v2220.lua") 
HypeMan.sendBotMessage("Red Iberia Marker Handlers Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\handlemarkers.lua") 
env.info("Loading Airboss")
HypeMan.sendBotMessage("Red Iberia Airboss Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\airboss.lua") 
env.info("Loading Airgen")
HypeMan.sendBotMessage("Red Iberia AI Sweep Generator Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\AI_GENERATOR.lua") 
env.info("Loading DCS LInk")
HypeMan.sendBotMessage("Red Iberia DCS to Website Link Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\dcslink.lua") 
HypeMan.sendBotMessage("Red Iberia Hazel Link Loading.....")
dofile(lfs.writedir() .."rib\\scripts\\cinc_loader.lua") 
HypeMan.sendBotMessage("Red Iberia Hazel Link Starting.....")
CinCServer.start("139.99.144.189", 3050)
HypeMan.sendBotMessage("Red Iberia: ALL SCRIPTS LOADED, INITALIZATION SHOULD BE ALMOST DONE.. HAVE A GOOD 8 HRS.")