-- this script handles our slot blocking items
-- it has some minor CTLD items due to it being easier
-- to have it run in this then in other places.


env.info("--------------RED IBERIA SLOTS CONTROLLER----------------------")
env.info("--------------By Robert Graham for TGW -------------------")
env.info("--------------LAST CHANGED IN VER: 2.2.20 -------------------")
env.info("--------------USES MOOSE AND CTDL ------------------------")

trigger.action.setUserFlag("SSB",100) -- turn slot blocker on.
------------ SLOT BLOCKING FUNCTIONS ----------------
-----------------------------------------------------
--


function allowredsochi()
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #002",0)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #003",0)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI",0)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #001",0)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #002",0)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #004",0)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #003",0)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #002",0)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #003",0)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI",0)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #001",0)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #002",0)
    trigger.action.setUserFlag("RUS MIG19 COLD",0)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #003",0)
    trigger.action.setUserFlag("RUS MIG19 COLD #001",0)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS MIG21 COLD - SOCHI",0)
    trigger.action.setUserFlag("CHINA  J11 COLD - SOCHI",0)
    trigger.action.setUserFlag("CHINA  J11 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #002",0)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS MIG15 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS MIG15 COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #003",0)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #002",0)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI #003",0)
    trigger.action.setUserFlag("RUS F14 COLD- SOCHI #002",0)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI #001",0)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI",0)
    trigger.action.setUserFlag("RUS F14 C&D - SOCHI #001",0)
    trigger.action.setUserFlag("RUS F14 C&D - SOCHI",0)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #003",0)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #002",0)
    trigger.action.setUserFlag("RUS A10C C&D #003",0)
    trigger.action.setUserFlag("RUS A10C C&D #002",0)
    trigger.action.setUserFlag("RUS A10C C&D #001",0)
    trigger.action.setUserFlag("RUS A10C C&D",0)
    trigger.action.setUserFlag("RUS A10C COLD #002",0)
    trigger.action.setUserFlag("RUS A10C COLD #001",0)
    trigger.action.setUserFlag("RUS A10C COLD",0)
    trigger.action.setUserFlag("RUS A10C COLD #003",0)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #004",0)
    trigger.action.setUserFlag("RUS JF17 COLD SOCHI",0)
    trigger.action.setUserFlag("RUS F-5E C&D SOCHI",0)
    trigger.action.setUserFlag("RUS F-5E COLD SOCHI ",0)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #003",0)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #002",0)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #001",0)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI",0)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #003",0)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #002",0)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #001",0)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI",0)
    trigger.action.setUserFlag("RUS F-5E COLD SOCHI  #002",0)
    trigger.action.setUserFlag("RUS JF17 COLD SOCHI #001",0)
    trigger.action.setUserFlag("RUS F-5E C&D SOCHI #001",0)
    trigger.action.setUserFlag("RUS JF17 C&D SOCHI #001",0)
    trigger.action.setUserFlag("RUS JF17 C&D SOCHI",0)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #004",0)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #003",0)    
    trigger.action.setUserFlag("RUS UH-1 SOCHI",0)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #001",0)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #002",0)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #003",0)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #001",0)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #004",0)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #002",0)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #003",0)
    BASE:E({"Red Slots allowed at Sochi"})
    SCHEDULER:New(nil,function()
      BASE:E({"GUD FOB SHOULD BE SPAWNING"}) 
      local _unitId = ctld.getNextUnitId()
      local _name = "ctld GUD FOB #" .. _unitId
      local _crate = {
        ["category"] = "Fortifications",
        ["type"] = "outpost",
        --  ["unitId"] = _unitId,
        ["y"] = dso.z,
        ["x"] = dso.x,
        ["name"] = _name,
        ["canCargo"] = false,
        ["heading"] = 0,
        }
      _crate["country"] = RedHq:GetCountry()
      mist.dynAddStatic(_crate)
      local _fob = StaticObject.getByName(_crate["name"])
      table.insert(ctld.logisticUnits, _fob:getName())
      table.insert(ctld.builtFOBS, _fob:getName())
      MESSAGE:New("Sochi was retaken, Slots Unlocked on Red Side, Logistics Building Avalible",15):ToRed()
      MESSAGE:New("Sochi was retaken by Russia, Slots Unlocked on Red Side",15):ToBlue()
      BASE:E({"Sochi FOB SHOULD BE SPAWNED"})
    end,{},30)
  end

function disableredsochi()
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #002",100)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI #003",100)
    trigger.action.setUserFlag("RUS F-18 COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI",100)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #001",100)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #002",100)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #004",100)
    trigger.action.setUserFlag("RUS M2000 C&D - SOCHI #003",100)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #002",100)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS M2000 COLD - SOCHI #003",100)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI",100)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #001",100)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #002",100)
    trigger.action.setUserFlag("RUS MIG19 COLD",100)
    trigger.action.setUserFlag("RUS F-18 C&D - SOCHI #003",100)
    trigger.action.setUserFlag("RUS MIG19 COLD #001",100)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS MIG21 COLD - SOCHI",100)
    trigger.action.setUserFlag("CHINA  J11 COLD - SOCHI",100)
    trigger.action.setUserFlag("CHINA  J11 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #002",100)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS MIG15 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS MIG15 COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #003",100)
    trigger.action.setUserFlag("RUS MIG29A COLD - SOCHI #002",100)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI #003",100)
    trigger.action.setUserFlag("RUS F14 COLD- SOCHI #002",100)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI #001",100)
    trigger.action.setUserFlag("RUS F14 COLD - SOCHI",100)
    trigger.action.setUserFlag("RUS F14 C&D - SOCHI #001",100)
    trigger.action.setUserFlag("RUS F14 C&D - SOCHI",100)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #003",100)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #002",100)
    trigger.action.setUserFlag("RUS A10C C&D #003",100)
    trigger.action.setUserFlag("RUS A10C C&D #002",100)
    trigger.action.setUserFlag("RUS A10C C&D #001",100)
    trigger.action.setUserFlag("RUS A10C C&D",100)
    trigger.action.setUserFlag("RUS A10C COLD #002",100)
    trigger.action.setUserFlag("RUS A10C COLD #001",100)
    trigger.action.setUserFlag("RUS A10C COLD",100)
    trigger.action.setUserFlag("RUS A10C COLD #003",100)
    trigger.action.setUserFlag("RUS SU27 COLD - SOCHI #004",100)
    trigger.action.setUserFlag("RUS JF17 COLD SOCHI",100)
    trigger.action.setUserFlag("RUS F-5E C&D SOCHI",100)
    trigger.action.setUserFlag("RUS F-5E COLD SOCHI ",100)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #003",100)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #002",100)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI #001",100)
    trigger.action.setUserFlag("RUS SU-25T COLD SOCHI",100)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #003",100)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #002",100)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI #001",100)
    trigger.action.setUserFlag("RUS SU-25 COLD SOCHI",100)
    trigger.action.setUserFlag("RUS F-5E COLD SOCHI  #002",100)
    trigger.action.setUserFlag("RUS JF17 COLD SOCHI #001",100)
    trigger.action.setUserFlag("RUS F-5E C&D SOCHI #001",100)
    trigger.action.setUserFlag("RUS JF17 C&D SOCHI #001",100)
    trigger.action.setUserFlag("RUS JF17 C&D SOCHI",100)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #004",100)
    trigger.action.setUserFlag("RUS F16 - COLD - SOCHI #003",100)    
    trigger.action.setUserFlag("RUS UH-1 SOCHI",100)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #001",100)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #002",100)
    trigger.action.setUserFlag("RUS UH-1 SOCHI #003",100)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #001",100)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #004",100)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #002",100)
    trigger.action.setUserFlag("RUS KA-50 SOCHI #003",100)
    MESSAGE:New("Sochi was lost to Coalition forces, Slots locked on Red Side",15):ToAll()
    BASE:E({"Red Slots disallowed at Sochi"})
  end
  
--- Allows Blue Slots at kobuletie
  -- @param nil
  function allowbluekob()
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB",0)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #001",0)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #002",0)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #003",0)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB",0)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #001",0)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #002",0)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #003",0)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #002",0)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #001",0)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #003",0)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB",0)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB",0)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB #001",0)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB",0)
    trigger.action.setUserFlag("SWD - AJS37 - COLD",0)
    trigger.action.setUserFlag("SWD - AJS37 - COLD #001",0)
    trigger.action.setUserFlag("SWD - AJS37 - C&D #001",0)
    trigger.action.setUserFlag("SWD - AJS37 - C&D",0)
    trigger.action.setUserFlag("USMC F-18 COLD - KOB #001",0)
    trigger.action.setUserFlag("USMC F-18 COLD - KOB",0)
    trigger.action.setUserFlag("USMC F-18 C&D - KOB #001",0)
    trigger.action.setUserFlag("USMC F-18 C&D - KOB",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #001",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #002",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #003",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #004",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #005",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #006",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #007",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #001",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #002",0)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #003",0)
    BASE:E({"Blue Slots allowed at Kobuletie"})
  end
  --- disables blue forces at kobulette.
  -- @param nil.
  function disallowbluekob()
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB",100)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #001",100)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #002",100)
    trigger.action.setUserFlag("RAAF F-18 COLD - KOB #003",100)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB",100)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #001",100)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #002",100)
    trigger.action.setUserFlag("RAAF F-18 C&D - KOB #003",100)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #002",100)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #001",100)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB #003",100)
    trigger.action.setUserFlag("USN F-14 VF103 COLD - KOB",100)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB",100)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB #001",100)
    trigger.action.setUserFlag("USN F-14 VF103 C&D - KOB",100)
    trigger.action.setUserFlag("SWD - AJS37 - COLD",100)
    trigger.action.setUserFlag("SWD - AJS37 - COLD #001",100)
    trigger.action.setUserFlag("SWD - AJS37 - C&D #001",100)
    trigger.action.setUserFlag("SWD - AJS37 - C&D",100)
    trigger.action.setUserFlag("USMC F-18 COLD - KOB #001",100)
    trigger.action.setUserFlag("USMC F-18 COLD - KOB",100)
    trigger.action.setUserFlag("USMC F-18 C&D - KOB #001",100)
    trigger.action.setUserFlag("USMC F-18 C&D - KOB",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #001",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #002",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #003",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #004",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #005",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #006",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - COLD #007",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #001",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #002",100)
    trigger.action.setUserFlag("USAF - F16 - Kob - C&D #003",100)
    BASE:E({"Blue Slots Blocked at Kobulete"})
  end

--- Allow Blue slots to be open
-- @param nil.
function allowbluesen()
  trigger.action.setUserFlag("USAF - A10C C&D",0)
  trigger.action.setUserFlag("USAF - A10C C&D #001",0)
  trigger.action.setUserFlag("USAF - A10C C&D #002",0)
  trigger.action.setUserFlag("USAF - A10C C&D #003",0)
  trigger.action.setUserFlag("USAF - A10C C&D #004",0)
  trigger.action.setUserFlag("USAF - A10C COLD",0)
  trigger.action.setUserFlag("USAF - A10C COLD #002",0)
  trigger.action.setUserFlag("USAF - A10C COLD #001",0)
  trigger.action.setUserFlag("USAF - A10C COLD #003",0)
  trigger.action.setUserFlag("USAF A10A C&D",0)
  trigger.action.setUserFlag("USAF A10A C&D #001",0)
  trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #001",0)
  trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #002",0)
  trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI",0)
  trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #003",0)
  trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI",0)
  trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #001",0)
  trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #002",0)
  trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #003",0)
  trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI",0)
  trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #001",0)
  trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #002",0)
  trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #003",0)
  trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #003",0)
  trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI",0)
  trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #001",0)
  trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #002",0)
  trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI",0)
  trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #001",0)
  trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #002",0)
  trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #003",0)
  trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki",0)
  trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #001",0)
  trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #002",0)
  trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #003",0)
  trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki",0)
  trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki #001",0)
  trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki #002",0)
  trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI",0)
  trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #001",0)
  trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #002",0)
  trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #003",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - COLD",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #001",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #002",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #003",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - C&D",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #001",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #002",0)
  trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #003",0)
BASE:E({"Blue Slots opened at Senaki"})
end

--- block blue slots at senaki.
function disallowbluesen()
            trigger.action.setUserFlag("USAF - A10C C&D",100)
            trigger.action.setUserFlag("USAF - A10C C&D #001",100)
            trigger.action.setUserFlag("USAF - A10C C&D #002",100)
            trigger.action.setUserFlag("USAF - A10C C&D #003",100)
            trigger.action.setUserFlag("USAF - A10C C&D #004",100)
            trigger.action.setUserFlag("USAF - A10C COLD",100)
            trigger.action.setUserFlag("USAF - A10C COLD #002",100)
            trigger.action.setUserFlag("USAF - A10C COLD #001",100)
            trigger.action.setUserFlag("USAF - A10C COLD #003",100)
            trigger.action.setUserFlag("USAF A10A C&D",100)
            trigger.action.setUserFlag("USAF A10A C&D #001",100)
            trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #001",100)
            trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #002",100)
            trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI",100)
            trigger.action.setUserFlag("GAF SU-25 COLD - SENAKI #003",100)
            trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI",100)
            trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #001",100)
            trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #002",100)
            trigger.action.setUserFlag("GAF SU-25T COLD - SENAKI #003",100)
            trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI",100)
            trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #001",100)
            trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #002",100)
            trigger.action.setUserFlag("UAF SU-27 COLD - SENAKI #003",100)
            trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #003",100)
            trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI",100)
            trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #001",100)
            trigger.action.setUserFlag("USMC AV-8B C&D - SENAKI #002",100)
            trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI",100)
            trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #001",100)
            trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #002",100)
            trigger.action.setUserFlag("USMC AV-8B COLD - SENAKI #003",100)
            trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki",100)
            trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #001",100)
            trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #002",100)
            trigger.action.setUserFlag("GAF MIG-15 COLD - Senaki #003",100)
            trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki",100)
            trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki #001",100)
            trigger.action.setUserFlag("GAF MIG-21 COLD - Senaki #002",100)
            trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI",100)
            trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #001",100)
            trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #002",100)
            trigger.action.setUserFlag("GAF MIG-19 COLD - SENAKI #003",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - COLD",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #001",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #002",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - COLD #003",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - C&D",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #001",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #002",100)
            trigger.action.setUserFlag("USAF - F16 - Senaki - C&D #003",100)
            BASE:E({"blue slots closed at Senaki"})
end

--- allow blue kutusi slots
function allowbluekut()
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI",0)
  trigger.action.setUserFlag("USAF F-15C COLD #002",0)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #003",0)
  trigger.action.setUserFlag("USAF F-15C COLD #001",0)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #002",0)
  trigger.action.setUserFlag("USAF F-15C COLD",0)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi",0)
  trigger.action.setUserFlag("USAF F-15C COLD #004",0)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #001",0)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #001",0)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #003",0)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #002",0)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI",0)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #001",0)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #002",0)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #003",0)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI",0)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #003",0)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #001",0)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #004",0)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #002",0)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #001",0)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #002",0)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #003",0)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #001",0)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI",0)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #003",0)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #002",0)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #001",0)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI",0)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #003",0)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #002",0)
            BASE:E({"Blue slots open at Kutaisi"})
end

--- block blue slots at kutaisi
function disallowbluekut()
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI",100)
  trigger.action.setUserFlag("USAF F-15C COLD #002",100)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #003",100)
  trigger.action.setUserFlag("USAF F-15C COLD #001",100)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #002",100)
  trigger.action.setUserFlag("USAF F-15C COLD",100)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi",100)
  trigger.action.setUserFlag("USAF F-15C COLD #004",100)
  trigger.action.setUserFlag("USAF F-15C C&D - Kutaisi #001",100)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #001",100)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #003",100)
  trigger.action.setUserFlag("USAF F-5E C&D - KUTAISI #002",100)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI",100)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #001",100)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #002",100)
  trigger.action.setUserFlag("USAF F-5E COLD - KUTAISI #003",100)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI",100)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #003",100)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #001",100)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #004",100)
  trigger.action.setUserFlag("FAF M2000 COLD - KUTAISI #002",100)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #001",100)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #002",100)
  trigger.action.setUserFlag("FAF M2000 C&D - KUTAISI #003",100)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #001",100)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI",100)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #003",100)
  trigger.action.setUserFlag("UAF MIG-29S COLD - KUTAISI #002",100)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #001",100)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI",100)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #003",100)
  trigger.action.setUserFlag("UAF MIG-29A COLD - KUTAISI #002",100)
  BASE:E({"Blue slots closed at kutasi"})
end

--- open blue slots at Sukhumi
function allowbluesuk()
  trigger.action.setUserFlag("UA - MI8 - Sukhumi - Cold",0)
  trigger.action.setUserFlag("UA - MI8 - Sukhumi - Cold #001",0)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold",0)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #001",0)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #002",0)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #003",0)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold",0)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #001",0)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #002",0)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #003",0)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D",0)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #001",0)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #002",0)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #003",0)
  trigger.action.setUserFlag("RAAF - SUK C&D",0)
  trigger.action.setUserFlag("RAAF - SUK C&D #001",0)
  trigger.action.setUserFlag("RAAF - SUK C&D #002",0)
  trigger.action.setUserFlag("USAF - F16 SUK C&D",0)
  trigger.action.setUserFlag("USAF - F16 SUK C&D #001",0)
  trigger.action.setUserFlag("USAF - F16 SUK C&D #002",0)
  trigger.action.setUserFlag("RAA SA342MINI",0)
  trigger.action.setUserFlag("RAA SA342MINI #001",0)
  trigger.action.setUserFlag("RAA KA50",0)
  trigger.action.setUserFlag("RAA KA50 #001",0)
  trigger.action.setUserFlag("RAA Huey Suk",0)
  trigger.action.setUserFlag("RAA Huey Suk #001",0)
  BASE:E({"Blue Slots Should be Open at Suk"})
  slzc:Explosion(300,0)
  BASE:E({"SUK FOB SCHEDULER STARTING 30 SECONDS"})
  
  SCHEDULER:New(nil,function() 
    BASE:E({"SUK FOB SHOULD BE SPAWNING"})
    local _unitId = ctld.getNextUnitId()
    local _name = "ctld Sukhimi FOB #" .. _unitId
    local _crate = {
      ["category"] = "Fortifications",
      ["type"] = "outpost",
      --  ["unitId"] = _unitId,
      ["y"] = slzc.z,
      ["x"] = slzc.x,
      ["name"] = _name,
      ["canCargo"] = false,
      ["heading"] = 0,
      }
    _crate["country"] = BlueHq:GetCountry()
    mist.dynAddStatic(_crate)
    local _fob = StaticObject.getByName(_crate["name"])
    table.insert(ctld.logisticUnits, _fob:getName())
    table.insert(ctld.builtFOBS, _fob:getName())
    MESSAGE:New("Sukhimi Slots Unlocked on Blue Side, Logistics Building Avalible",15):ToBlue()
    BASE:E({"SUK FOB SHOULD BE SPAWNED"})
    end,{},30)
end

--- close red slots at sukhumi
function disallowredsuk()
  trigger.action.setUserFlag("RUS F18C - SUK C&D",100)
  trigger.action.setUserFlag("RUS F18C - SUK C&D #001",100)
  trigger.action.setUserFlag("RUS - Huey - Suk #001",100)
  trigger.action.setUserFlag("RUS - Huey - Suk",100)
  BASE:E({"Red Slots Should be Closed at Suk"})
end

--- close blue slots at sukhumi
function disallowbluesuk()
  trigger.action.setUserFlag("UA - MI8 - Sukhumi - Cold",100)
  trigger.action.setUserFlag("UA - MI8 - Sukhumi - Cold #001",100)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold",100)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #001",100)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #002",100)
  trigger.action.setUserFlag("UA - KA50 - Sukhumi - Cold #003",100)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold",100)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #001",100)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #002",100)
  trigger.action.setUserFlag("USAA - UH1 - Sukhumi - Cold #003",100)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D",100)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #001",100)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #002",100)
  trigger.action.setUserFlag("USAF - A10C - SUK C&D #003",100)
  trigger.action.setUserFlag("RAAF - SUK C&D",100)
  trigger.action.setUserFlag("RAAF - SUK C&D #001",100)
  trigger.action.setUserFlag("RAAF - SUK C&D #002",100)
  trigger.action.setUserFlag("USAF - F16 SUK C&D",100)
  trigger.action.setUserFlag("USAF - F16 SUK C&D #001",100)
  trigger.action.setUserFlag("USAF - F16 SUK C&D #002",100)
  trigger.action.setUserFlag("RAA SA342MINI",100)
  trigger.action.setUserFlag("RAA SA342MINI #001",100)
  trigger.action.setUserFlag("RAA KA50",100)
  trigger.action.setUserFlag("RAA KA50 #001",100)
  trigger.action.setUserFlag("RAA Huey Suk",100)
  trigger.action.setUserFlag("RAA Huey Suk #001",100)
  BASE:E({"Blue Slots Should be Closed at Suk"})
end

--- open red slots at sukhumi.
function allowredsuk()
  trigger.action.setUserFlag("RUS F18C - SUK C&D",0)
  trigger.action.setUserFlag("RUS F18C - SUK C&D #001",0)
  trigger.action.setUserFlag("RUS - Huey - Suk #001",0)
  trigger.action.setUserFlag("RUS - Huey - Suk",0)
  BASE:E({"Red Slots Should be open at Suk"})
    slzc:Explosion(300,0)
    BASE:E({"SUK FOB SHOULD BE SPAWNING 30 seconds"})
  
    SCHEDULER:New(nil,function() 
    BASE:E({"SUK FOB SHOULD BE SPAWNING"})
    local _unitId = ctld.getNextUnitId()
    local _name = "ctld Sukhimi FOB #" .. _unitId
    local _crate = {
      ["category"] = "Fortifications",
      ["type"] = "outpost",
      --  ["unitId"] = _unitId,
      ["y"] = slzc.z,
      ["x"] = slzc.x,
      ["name"] = _name,
      ["canCargo"] = false,
      ["heading"] = 0,
      }
    _crate["country"] = RedHq:GetCountry()
    mist.dynAddStatic(_crate)
    local _fob = StaticObject.getByName(_crate["name"])
    table.insert(ctld.logisticUnits, _fob:getName())
    table.insert(ctld.builtFOBS, _fob:getName())
    MESSAGE:New("Sukhimi Slots Unlocked on Blue Side, Logistics Building Avalible",15):ToRed()
    BASE:E({"SUK FOB SHOULD BE SPAWNED"})
    end,{},30)
end

--- open blue slots at gudauta
function allowbluegud()
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold",0)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #001",0)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #002",0)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #003",0)
  trigger.action.setUserFlag("USAA - UH1 - Gudauta - Cold",0)
  trigger.action.setUserFlag("USAA - UH1 - Gudauta - Cold #001",0)
  trigger.action.setUserFlag("UA - MI8 - Gudauta - Cold",0)
  trigger.action.setUserFlag("UA - MI8 - Gudauta - Cold #001",0)
  trigger.action.setUserFlag("USAF - F18 - C&D - GUD",100)
  trigger.action.setUserFlag("USAF - F18 - C&D - GUD #001",100)
  BASE:E({"Blue Slots should be open at Gudauta"})
  glzc:Explosion(300,0)
  BASE:E({"Gud GUD SHOULD BE SPAWNING 30 SECONDS"})
  
  SCHEDULER:New(nil,function() 
    BASE:E({"GUD FOB SHOULD BE SPAWNING"})
    local _unitId = ctld.getNextUnitId()
    local _name = "ctld Gud FOB #" .. _unitId
    local _crate = {
      ["category"] = "Fortifications",
      ["type"] = "outpost",
      --  ["unitId"] = _unitId,
      ["y"] = glzc.z,
      ["x"] = glzc.x,
      ["name"] = _name,
      ["canCargo"] = false,
      ["heading"] = 0,
      }
    _crate["country"] = BlueHq:GetCountry()
    mist.dynAddStatic(_crate)
    local _fob = StaticObject.getByName(_crate["name"])
    table.insert(ctld.logisticUnits, _fob:getName())
    table.insert(ctld.builtFOBS, _fob:getName())
    MESSAGE:New("Guduata Slots Unlocked on Blue Side, Logistics Building Avalible",15):ToBlue()
    BASE:E({"GUD FOB SHOULD BE SPAWNED"})
    end,{},30)
end

--- close red slots at gudauta
function disallowredgud()
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D",100)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #001",100)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #002",100)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #003",100)
  trigger.action.setUserFlag("RUS - KA50 GUD",100)
  trigger.action.setUserFlag("RUS - KA50 GUD #001",100)
  trigger.action.setUserFlag("RUS - MI8 GUD",100)
  trigger.action.setUserFlag("RUS - MI8 GUD #001",100)
  trigger.action.setUserFlag("RUS - JF17 - GUD C&D",100)
  trigger.action.setUserFlag("RUS - JF17 - GUD C&D #001",100)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D",100)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #002",100)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #001",100)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #003",100)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #004",100)
  trigger.action.setUserFlag("RUS - Huey - Gud #003",100)
  trigger.action.setUserFlag("RUS - Huey - Gud #002",100)
  trigger.action.setUserFlag("RUS - Huey - Gud #001",100)
  trigger.action.setUserFlag("RUS - Huey - Gud",100)
    trigger.action.setUserFlag("RUS - F/A-16C - GUD - C&D #001",100)
  trigger.action.setUserFlag("RUS - F/A-16C - GUD - C&D",100)
  BASE:E({"Red Slots should be closed at Gudauta"})
end

--- close blue slots at gudauta
function disallowbluegud()
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold",100)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #001",100)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #002",100)
  trigger.action.setUserFlag("UA - KA50 - Gudauta - Cold #003",100)
  trigger.action.setUserFlag("USAA - UH1 - Gudauta - Cold",100)
  trigger.action.setUserFlag("USAA - UH1 - Gudauta - Cold #001",100)
  trigger.action.setUserFlag("UA - MI8 - Gudauta - Cold",100)
  trigger.action.setUserFlag("UA - MI8 - Gudauta - Cold #001",100)
  trigger.action.setUserFlag("USAF - F18 - C&D - GUD",100)
  trigger.action.setUserFlag("USAF - F18 - C&D - GUD #001",100)
  BASE:E({"Blue Slots Should be closed at Gud"})
end

--- open red slots at guduata
function allowredgud()
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D",0)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #001",0)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #002",0)
  trigger.action.setUserFlag("RUS - A-10C - GUD C&D #003",0)
  trigger.action.setUserFlag("RUS - KA50 GUD",0)
  trigger.action.setUserFlag("RUS - KA50 GUD #001",0)
  trigger.action.setUserFlag("RUS - MI8 GUD",0)
  trigger.action.setUserFlag("RUS - MI8 GUD #001",0)
  trigger.action.setUserFlag("RUS - JF17 - GUD C&D",0)
  trigger.action.setUserFlag("RUS - JF17 - GUD C&D #001",0)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D",0)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #002",0)
  trigger.action.setUserFlag("RUS - F/A-16C - GUD - C&D #001",0)
  trigger.action.setUserFlag("RUS - F/A-16C - GUD - C&D",0)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #001",0)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #003",0)
  trigger.action.setUserFlag("RUS - F/A-18C - GUD C&D #004",0)
  trigger.action.setUserFlag("RUS - Huey - Gud #003",0)
  trigger.action.setUserFlag("RUS - Huey - Gud #002",0)
  trigger.action.setUserFlag("RUS - Huey - Gud #001",0)
  trigger.action.setUserFlag("RUS - Huey - Gud",0)
  BASE:E({"Red slots should be open at Gud."})
  glzc:Explosion(300,0)
  BASE:E({"GUD FOB SHOULD BE SPAWNING 30 SECONDS"})
  
  SCHEDULER:New(nil,function()
    BASE:E({"GUD FOB SHOULD BE SPAWNING"}) 
    local _unitId = ctld.getNextUnitId()
    local _name = "ctld GUD FOB #" .. _unitId
    local _crate = {
      ["category"] = "Fortifications",
      ["type"] = "outpost",
      --  ["unitId"] = _unitId,
      ["y"] = glzc.z,
      ["x"] = glzc.x,
      ["name"] = _name,
      ["canCargo"] = false,
      ["heading"] = 0,
      }
    _crate["country"] = RedHq:GetCountry()
    mist.dynAddStatic(_crate)
    local _fob = StaticObject.getByName(_crate["name"])
    table.insert(ctld.logisticUnits, _fob:getName())
    table.insert(ctld.builtFOBS, _fob:getName())
    MESSAGE:New("Guduata Slots Unlocked on Red Side, Logistics Building Avalible",15):ToRed()
    BASE:E({"GUD FOB SHOULD BE SPAWNED"})
    end,{},30)
end