env.info("Red Iberia Ver 2.0")
env.info("Mission by Robert Graham")
env.info("Mission Script Loader Active")
env.info("Loading MOOSE")

pcall(function() dofile(lfs.writedir() .."rib\\scripts\\Moose.lua") end,nil)
env.info("Loading MIST")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\mist_4_3_74.lua") end,nil)
env.info("Loading Peristence")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\persistence.lua") end,nil)
env.info("Loading Globals")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\globals.lua") end,nil)
env.info("Loading Rutils")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\rutils.lua") end,nil)
env.info("Loading Slotblocker")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\slotblocking.lua") end,nil)
env.info("Loading A2ACap")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\a2acap.lua") end,nil)
env.info("Loading Groupsaving")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\simple_groupsaving.lua") end,nil)
env.info("Loading CTLD")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\CTLD.lua") end,nil)
env.info("Loading CTLD SAVE")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\ctldsave.lua") end,nil)
env.info("Loading CTLD STATIC SAVE")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\ctld_static_save.lua") end,nil)
env.info("Loading CTLD SCENERY")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\simple_scenery_persistence.lua") end,nil)
env.info("Loading RIB SAVE")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\ribsave.lua") end,nil)
env.info("Loading Main")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\main_no_cv_v2220.lua") end,nil)
env.info("Loading Airboss")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\airboss.lua") end,nil)
env.info("Loading Airgen")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\AIR_GENERATOR.lua") end,nil)
env.info("Loading DCS LInk")
pcall(function() dofile(lfs.writedir() .."rib\\scripts\\dcslink.lua") end,nil)



